
to_cat = 'general-discussion'
copy_cat('general-discussion/debates', to_cat)
copy_cat('general-discussion/general-questions', to_cat)
copy_cat('general-discussion/homework-help', to_cat)
copy_cat('general-discussion/news', to_cat)
copy_cat('general-discussion/off-topic-spam', to_cat)
copy_cat('downloads/download-requests', to_cat)
copy_cat('downloads', to_cat)
copy_cat('reviews-and-multimedia', to_cat)
copy_cat('music', to_cat)
copy_cat('tutorials-tips-tricks-and-tweaks', to_cat)
copy_cat('vehicles', to_cat)

to_cat = 'technology'
copy_cat('smart-phones', to_cat)
copy_cat('computer-hardware-discussion', to_cat)
copy_cat('electronics', to_cat)
copy_cat('linux', to_cat)
copy_cat('3rd-party-programs', to_cat)

to_cat = 'community-suggestions'
copy_cat('community-suggestions/resolved-suggestions', to_cat)
copy_cat('site-feedback', to_cat)
copy_cat('site-updates-and-news', to_cat)
copy_cat('general-site-discussions', to_cat)

to_cat = 'graphics'
copy_cat('graphics/graphics-requests-and-help', to_cat)
copy_cat('graphics/graphic-tutorials', to_cat)

to_cat = 'general-programming'
copy_cat('general-programming/java-programming', to_cat)
copy_cat('web-design-development', to_cat)
copy_cat('appbak', to_cat)
copy_cat('ideas-for-apps', to_cat)
copy_cat('page-plus-balance', to_cat)

to_cat = 'game-development'
copy_cat('gamedev-general-discussion', to_cat)
copy_cat('game-elements', to_cat)
copy_cat('game-mechanics-and-content', to_cat)
copy_cat('engine-development', to_cat)
copy_cat('networking-and-multiplayer', to_cat)
copy_cat('3d-resources', to_cat)
copy_cat('client-help', to_cat)
copy_cat('effects-and-sprites', to_cat)
copy_cat('arcade-room', to_cat)
copy_cat('sounds-and-music', to_cat)
copy_cat('development-progress', to_cat)
copy_cat('contest-board', to_cat)
copy_cat('game-tools-and-utilities', to_cat)
copy_cat('newbie-questions', to_cat)
copy_cat('teams', to_cat)
copy_cat('tutorials-and-code', to_cat)
copy_cat('storylines-quests-and-missions', to_cat)

to_cat = 'games'
copy_cat('games/guides', to_cat)
copy_cat('games/wurm-unlimited', to_cat)

to_cat = 'minecraft'
copy_cat('minecraft-tutorials', to_cat)
copy_cat('moparcraft-infraction-reports', to_cat)
copy_cat('games/minecraft', to_cat)
copy_cat('games/minecraft-discussion', to_cat)
copy_cat('games/minecraft-server-advertisements', to_cat)
copy_cat('games/moparcraft-discussion', to_cat)
copy_cat('games/solved-reports', to_cat)
copy_cat('whitelist-applications', to_cat)

to_cat = 'runescape'
copy_cat('guides', to_cat)
copy_cat('runescape2-client-hacking-tips', to_cat)
copy_cat('runescape-classic-server-advertisement', to_cat)
copy_cat('runescape-classic-server-and-client-help', to_cat)
copy_cat('server-advertisements', to_cat)
copy_cat('server-and-client-development-showoff', to_cat)
copy_cat('server-help', to_cat)
copy_cat('server-tutorials/featured-tutorials', to_cat)
copy_cat('server-tutorials/snippets', to_cat)
copy_cat('server-tutorials', to_cat)
copy_cat('rs-client-hacking', to_cat)
copy_cat('rsc-server-development-discussion', to_cat)
copy_cat('rs-models/model-requests-help', to_cat)
copy_cat('rs-models', to_cat)
copy_cat('simba-and-script-help', to_cat)
copy_cat('simba-development', to_cat)
copy_cat('simba-faqs-and-tutorials', to_cat)
copy_cat('simba-first-scripts-section', to_cat)
copy_cat('simba-runescape-scripts', to_cat)
copy_cat('simba-scripting-help', to_cat)
copy_cat('simba-script-requests', to_cat)
copy_cat('other-simba-scripts', to_cat)
copy_cat('questions-and-talk-about-rs2-client-hacking', to_cat)
copy_cat('help-with-java-hacks-bots', to_cat)
copy_cat('games/rs2007-discussion', to_cat)
copy_cat('games/runescape', to_cat)
copy_cat('games/runescape-discussion', to_cat)
copy_cat('games/server-status-page', to_cat)
copy_cat('official-server-discussion', to_cat)
copy_cat('banners-and-backgrounds', to_cat)
copy_cat('download-simba-here', to_cat)
copy_cat('development-teams', to_cat)
copy_cat('general-server-discussion', to_cat)